### ISSUE TITLE
Full list of items for building pizza

### ISSUE THREAD

**Issue by ysz** [RespiraWorks/Ventilator#356]
We really need to start buying equipment to HiL testing.

**What has to be done**

Full list of items for building pizza (BOM?)

PS

Part of HiL Epic?

**Comment by martukas** [comment]
Currently all the documentation for the physical prototype is here:
https://github.com/RespiraWorks/SystemDesign/tree/master/4_Manufacturing_Design/Alpha_Build_Instructions#alpha-prototype

I can create another ticket for HiL testing equipment, but probably I'll do it in that repo also because hopefully more pneumatics people will join the discussion.
