### ISSUE TITLE
Investigate manifold to combine O2 sensor mount, venturi, and relief valve mount into one component

### ISSUE THREAD

**Issue by tijanim** [RespiraWorks/Ventilator#780]
Figure out if we can simplify this arrangment into a single printed manifold that allows mounting of relief valve, O2 sensor mount, and venturi that fits into the existing footprint. 
![image](https://user-images.githubusercontent.com/63751856/87816816-ea6c2800-c835-11ea-9b64-a01d0ee9cbd2.png)

**Comment by inceptionev** [comment]
Oxygen sensor should be close to the flow for best response, and as far downstream from the oxygen inlet as possible to allow for mixing.

The path should probably be something like this: oxygen inlet > relief valve > venturi > oxygen sensor.

**Comment by martukas** [comment]
* have a custom oxygen sensor adapter here: https://github.com/RespiraWorks/Ventilator/tree/master/manufacturing/oxygen#oxygen-sensor-sub-assembly
* This needs to be modified to include an adapter for the overpressure valve, which was selected in #656 
* It might also be a good idea to incorporate an additional elbow that redirects flow towards the front panel filter adapters, eliminating the need for one more McMaster elbow
* Integrating with the venturi is off the table because the venturis are upstream of the mixing chamber, and any further integration of manifolds is probably better left for after we have a definitive mixing chamber design (discussed in #915 )

**Comment by martukas** [comment]
This has been partly addressed in in #916
